### ISSUE TITLE
Error on Woocommerce Shop page

### ISSUE THREAD

**Issue by noralam** [rankmath/seo-by-rank-math#102]
**Describe the bug**
I want to use the Rank Math plugin in my WordPress site but I am showing the error on my Woocommerce shop page.

**To Reproduce**
1. The error is : Notice: Array to string conversion in /home/plnxbdhx/public_html/wp-content/plugins/seo-by-rank-math/includes/opengraph/class-image.php on line 531
2.  One More error showing when updating products.

**Expected behavior**
Now I can't use the plugin for the major error

**Screenshots**
Please see the screenshot https://prnt.sc/1ye337b

**Comment by surajv** [comment]
Hello @noralam,

On Shop, we use the Product archive image from Titles & Meta settings. It looks like on your setup, the `get_query_var( 'post_type' )` is returning `null` instead of Product.

Please open a support ticket from here https://support.rankmath.com/. Our support staff will help you.

Thank you.
