### ISSUE TITLE
Broken PHP in Plugin Update

### ISSUE THREAD

**Issue by revans-premier-education** [rankmath/seo-by-rank-math#194]
What's going on guys? This is the second time a plugin release/update has contained a core PHP syntax error, taking down our entire site completely. I've had to disable auto-updates now.

Issue is in class-taxonomy.php where the fourth param ($tax_name) has a trailing slash within the do_filter method call.

Parse error: syntax error, unexpected ')' in /home/XXXX/public_html/wp-content/plugins/seo-by-rank-math/includes/modules/sitemap/providers/class-taxonomy.php on line 150

```
$item = $this->do_filter(
        'sitemap/index/entry',
        [
                'loc'     => Router::get_base_url( $tax_name . '-sitemap' . $current_page . $
                'lastmod' => $query->have_posts() ? $query->posts[0]->post_modified_gmt : $l$
        ],
        'term',
        $tax_name,
);
```

Can you advise?

Many thanks in advanced.

**Comment by Moustachey** [comment]
Confirmed had this issue earlier today on a fresh local WP install. The same install worked on a slightly different install.
Didn't work on: php-7.2.19-Win32-VC15-x64
Worked on: 8.1.2-1ubuntu2.14

**Comment by balazsrm** [comment]
Hello @revans-premier-education & @Moustachey,

Thank you for reporting this issue, that was caused by a PHP 7.2 incompatibility issue in the code. We've been planning to increase the minimum PHP requirement to 7.3, and we made that step in version 1.0.202, so this issue is not relevant anymore. Please update your server to PHP version 7.3 or higher to keep using Rank Math.

Please note that even PHP 7.4 [has reached its end of life](https://www.php.net/supported-versions.php) and is not officially supported anymore. Recommended PHP version to use today is 8.2.
