### ISSUE TITLE
Add filter for "Please keep only one SEO plugin active..."

### ISSUE THREAD

**Issue by Log1x** [rankmath/seo-by-rank-math#53]
**Is your feature request related to a problem? Please describe.**
I would like to request a filter be added to change the plugins detected by the [plugin watcher](https://github.com/rankmath/seo-by-rank-math/blob/853e20399106d57200d26cd7eda17a1583eda0d5/includes/admin/watcher/class-watcher.php)

We use Redirection and have no intention of switching off of it. We understand the risk and have disabled things appropriately. To be honest, I'm not sure if Redirection should be included in this list to begin with.

**Describe the solution you'd like**
Either Redirection removed or a filter added to customize the plugins checked/watched.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by dvjrickkraft** [comment]
Just found this now too.  The Redirection plugin works perfectly right now, and the message is created by Rank Math. There's a message at the top of the dashboard after installing Redirection. "Please keep only one SEO plugin active, otherwise, you might lose your rankings and traffic. Click here to Deactivate." If you click Deactivate, Redirection is disabled... not good. :) Rank math is version 1.0.68. In testing, deactivating/reactivating Redirection brought back the message.

I deactivated Rank Math, the notice went away, and reactivated Rank Math, and the message didn't come back.
After, I de/reactivated Redirection, and the top message notification came back.
Environment

Firefox 89.0.2 64bit, WordPress Current version: 5.7.2 and Redirection plugin Version 5.1.2
![Capture](https://user-images.githubusercontent.com/5501662/126135715-212c7c09-0baf-46f8-b690-d2fe3ee2f930.JPG)
![Capture2](https://user-images.githubusercontent.com/5501662/126135737-0a909bac-49ad-4377-97c3-04dfc3d05e60.JPG)

**Comment by pratikmts** [comment]
Hello,

We show conflicting notice for the Redirection plugin only when the Redirection module is enabled in the Rank Math. Since you are using different plugin for the Redirection, you can disable the Redirection module from Dashboard >> Rank Math >> Modules page.

I hope that helps.

**Comment by pratikrm** [comment]
Closing it due to inactivity. Please reopen it if you still get the notice after disabling the Redirection module.
